name: api_models
description: API models
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.7.0


dev_dependencies:
  build_runner: ^2.3.0
  json_serializable: ^6.5.1
  mocktail: ^0.3.0
  test: ^1.21.6
  very_good_analysis: ^3.1.0
  
